language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
env:
  - DJANGO=1.4.22
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.11
  - DJANGO=1.8.13
install:
  - pip install -q Django==$DJANGO
  - pip install .
script:
  - python manage.py test geoposition
matrix:
  exclude:
    # Django doesn't support following combinations
    - python: 3.3
      env: DJANGO=1.4.22
    - python: 3.4
      env: DJANGO=1.4.22
    - python: 3.5
      env: DJANGO=1.4.22
    - python: 2.6
      env: DJANGO=1.7.11
    - python: 2.6
      env: DJANGO=1.8.13
